#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo '🏗️👷 Styling, testing and building your project before committing'

npx lint-staged

# Check ESLint Standards
yarn checker ||
(
    echo '🙈👷🔨❌ Yoo, your code looks disgusting. Check linter 🙈👷🔨❌
          Add changes and try commit again.';
    false;
)

# If there is no error linter, the codes will be commited
echo '🎉🎉🎉🎉 Yeayy, there is no error linter in your codes... I am committing this now. ✨🚀🏄‍♂️🍻'